DROP TABLE IF EXISTS consume_fact;
DROP TABLE IF EXISTS consumable;
DROP TABLE IF EXISTS consumable_model;
DROP TABLE IF EXISTS consumable_type;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS facility;
DROP SEQUENCE IF EXISTS users_seq;
DROP SEQUENCE IF EXISTS users_roles_seq;
DROP SEQUENCE IF EXISTS facility_seq;
DROP SEQUENCE IF EXISTS room_seq;
DROP SEQUENCE IF EXISTS consumable_type_seq;
DROP SEQUENCE IF EXISTS consumable_model_seq;
DROP SEQUENCE IF EXISTS consumable_seq;
DROP SEQUENCE IF EXISTS consume_fact_seq;

CREATE SEQUENCE users_seq START WITH 100000;
CREATE SEQUENCE users_roles_seq START WITH 100000;
CREATE SEQUENCE facility_seq START WITH 100000;
CREATE SEQUENCE room_seq START WITH 100000;
CREATE SEQUENCE consumable_type_seq START WITH 100000;
CREATE SEQUENCE consumable_model_seq START WITH 100000;
CREATE SEQUENCE consumable_seq START WITH 100000;
CREATE SEQUENCE consume_fact_seq START WITH 100000;

CREATE TABLE users
(
  	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE users_seq PRIMARY KEY,
  	name             VARCHAR(45)                 NOT NULL,
  	email            VARCHAR(255)                 NOT NULL,
  	password         VARCHAR(60)                 NOT NULL,
  	registered       TIMESTAMP DEFAULT now() NOT NULL,
  	enabled          BOOLEAN DEFAULT TRUE       NOT NULL,
			CONSTRAINT unique_user_idx UNIQUE (email)
);


CREATE TABLE users_roles
(
    user_role_id     INTEGER GENERATED BY DEFAULT AS SEQUENCE users_roles_seq PRIMARY KEY,
  	user_id          INTEGER                 NOT NULL,
   	role             VARCHAR(100),
   	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
			CONSTRAINT users_roles_idx UNIQUE ( user_id, role )
);

CREATE TABLE facility (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE facility_seq PRIMARY KEY,
	name            varchar(255)          NOT NULL,
	address          varchar(255)          NOT NULL UNIQUE,
	comments         varchar(255),
	CONSTRAINT unique_facility_idx UNIQUE (name, address)
);

CREATE TABLE room (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE room_seq PRIMARY KEY,
	name            varchar(255)          NOT NULL,
	facility_id      integer               NOT NULL,
	storage          boolean               NOT NULL,
	user_id          integer			   ,
	comments         varchar(255)          ,
	CONSTRAINT unique_room_idx UNIQUE (name, facility_id),
	FOREIGN KEY (facility_id) REFERENCES facility (id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE consumable_type (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE consumable_type_seq  PRIMARY KEY,
	name             varchar(255)          NOT NULL UNIQUE,
	comments         varchar(255)          
);

CREATE TABLE consumable_model (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE consumable_model_seq PRIMARY KEY,
	name             varchar(30)           NOT NULL,
	partnumber       varchar(30)           NOT NULL UNIQUE,
	consumable_type_id  INTEGER            NOT NULL,
	resource         integer               NOT NULL,
	FOREIGN KEY (consumable_type_id) REFERENCES consumable_type (id)
);

CREATE TABLE consumable (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE consumable_seq PRIMARY KEY,
	name             varchar(255)          NOT NULL,
	contract	    	 varchar(255),
	price            integer,
	consumable_model_id integer            NOT NULL,
	room_id			 		 INTEGER			   			 NOT NULL,
	status           integer               NOT NULL,
	FOREIGN KEY (consumable_model_id) REFERENCES consumable_model (id) ON DELETE SET NULL
);

CREATE TABLE consume_fact (
	id               INTEGER GENERATED BY DEFAULT AS SEQUENCE consume_fact_seq PRIMARY KEY,
	room_id			 INTEGER			   	NOT NULL,
	storage_id       INTEGER      NOT NULL,
	consumable_id    INTEGER              	NOT NULL,
	consumable_model_id INTEGER,
	date             DATE                 	NOT NULL,
  FOREIGN KEY (room_id) REFERENCES room (id),
	FOREIGN KEY (storage_id) REFERENCES room (id),
	FOREIGN KEY (consumable_model_id) REFERENCES consumable_model (id) ON DELETE SET NULL
);